version: 2

env:
  - GO111MODULE=on
builds:
  - main: main.go
    binary: nagios-slack
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz

nfpms:
  - package_name: nagios-slack
    vendor: Jason Hancock
    homepage: https://github.com/jasonhancock/nagios-slack
    maintainer: Jason Hancock <jason@jasonhancock.com>
    description: Slack notification plugin for Nagios
    formats:
      - deb
    bindir: /usr/bin
    epoch: 1
    release: 1
