name: release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build and Release
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release Version
        id: version
        run: |
          export RELEASE_VERSION=v0.0.${{ github.run_number }}
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "release_version=$RELEASE_VERSION" >> $GITHUB_OUTPUT

      - name: create tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a $RELEASE_VERSION -m $RELEASE_VERSION
          git push origin $RELEASE_VERSION

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: v2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
